// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(JPVerbLearnerContext))]
    [Migration("20250719170135_initial_migration")]
    partial class initial_migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("api.models.Verb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseHiragana")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BaseKanji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BaseRomaji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("JlptLevel")
                        .HasColumnType("integer");

                    b.Property<string>("TranslationFr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VerbeGroup")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Verb", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
